#!/usr/bin/env bash -x

OUTPUT_FILE_NAME=auto-export-proxy.sh

function insert_new_line()
{
	echo -e "\n">>$OUTPUT_FILE_NAME
}

function gen_export_proxy()
{
	if [ "$1" = "no_proxy" ]; then
		COUNT_NO_PROXY=`echo $no_proxy | grep "$2" | wc -w`
		if [ $COUNT_NO_PROXY -eq 0 ]; then
			temp_no_proxy="$no_proxy, $2"
    		echo "export no_proxy='$temp_no_proxy'"
		fi
	else
		echo "export $1=$2"
	fi
}

echo "#!/usr/bin/env bash" >$OUTPUT_FILE_NAME

insert_new_line

# insert shared and unique resources >>$OUTPUT_FILE_NAME
RES_LIST=`ls -1 ./resources | grep .resource`

for RES in $RES_LIST; do
	cat ./resources/$RES>>$OUTPUT_FILE_NAME
	insert_new_line
done

# insert shared functions>>$OUTPUT_FILE_NAME

cat ./defaults/public.fnc>>$OUTPUT_FILE_NAME
insert_new_line


FUNC_LIST=`ls -1 ./functions | grep .fnc`

# insert functions>>$OUTPUT_FILE_NAME
for FUNC in $FUNC_LIST; do
	CONTENT=`cat ./functions/${FUNC}`

	STORED_SSID_REPLACED=`echo ${FUNC%.*} | sed -e 's/-/_/g'`

	echo "${STORED_SSID_REPLACED}_${CONTENT}">>$OUTPUT_FILE_NAME

	insert_new_line
done

PROXY_LIST=`ls -1 ./settings | grep .settings`

# insert settings>>$OUTPUT_FILE_NAME
for PROXY in $PROXY_LIST; do
	FILENAME="./settings/${PROXY}"

	if [ -f $FILENAME ]; then
		STORED_SSID_REPLACED=`echo ${PROXY%.*} | sed -e 's/-/_/g'`

		# insert method declaretion
		echo "export_${STORED_SSID_REPLACED}()">>$OUTPUT_FILE_NAME
		echo "{">>$OUTPUT_FILE_NAME

		while read line; do
			read param value <<<${line}
			gen_export_proxy ${param} ${value}>>$OUTPUT_FILE_NAME
		done < $FILENAME

		echo "}">>$OUTPUT_FILE_NAME
	fi

	insert_new_line
done

# insert main function >>$OUTPUT_FILE_NAME
cat ./defaults/main.fnc>>$OUTPUT_FILE_NAME

cp -a ./$OUTPUT_FILE_NAME ~/$OUTPUT_FILE_NAME # copy to /home/